- apps/dsep/pages/signUp.tsx
- apps/dsnp/pages/checkoutPage.tsx
- apps/dsnp/pages/signUp.tsx
- apps/dsnp/utilities/detailsForm-utils.ts
1. https://fide-official.atlassian.net/browse/DSNP-76
2. https://fide-official.atlassian.net/browse/DSNP-77
3. https://fide-official.atlassian.net/browse/DUB-276
4. https://fide-official.atlassian.net/browse/DSNP-66
5. https://fide-official.atlassian.net/browse/DSNP-67
6. https://fide-official.atlassian.net/browse/TWH-692
> feat: added validation on signup page and price issue on checkout page

- apps/dsep/components/header/index.tsx
Added Header Value
remove Cart Icon and HomePage Icon
> feat: "remove cart icon and homePage Icon and added HeaderValue"

- apps/odr/components/UI/card/Card.tsx
- apps/odr/components/landingPage/LandingPage.tsx
- apps/odr/components/productDetails/CallToAction.tsx
- apps/odr/components/productDetails/DetailsSection.tsx
- apps/odr/components/signIn/SignIn.tsx
- apps/odr/lib/types/products.ts
- apps/odr/lib/types/responseModel.ts
- apps/odr/pages/_document.tsx
- apps/odr/pages/search.tsx
1. Search Integration
2. Landing Page UI
> feat: implemented search integration and some landing ui

- apps/odr/lib/types/responseModel.ts
- apps/odr/pages/checkoutPage.tsx
- apps/odr/pages/orderConfirmation.tsx
- apps/odr/pages/orderDetails.tsx
- apps/odr/utilities/checkout-utils.ts
- apps/odr/utilities/confirm-utils.ts
1. Integrated Init Api
2. Integrated Confirm API
> feat: api integration of init and confirm

- apps/odr/components/detailsCard/AddBillingButton.tsx
- apps/odr/components/detailsCard/AddConsentButton.tsx
- apps/odr/components/detailsCard/AddDisputeButton.tsx
- apps/odr/components/detailsCard/BillingForm.tsx
- apps/odr/components/detailsCard/ConsentForm.tsx
- apps/odr/components/detailsCard/DisputeForm.tsx
- apps/odr/components/loader/Loader.tsx
- apps/odr/components/orderHistory/MyCases.tsx
- apps/odr/components/productList/ProductList.tsx
- apps/odr/locales/en.ts
- apps/odr/pages/checkoutPage.tsx
> feat: ui development for odr

- apps/odr/components/detailsCard/DisputeForm.tsx
- apps/odr/components/detailsCard/ShippingForm.module.css
- apps/odr/components/productList/ProductList.tsx
- apps/odr/pages/orderConfirmation.tsx
- apps/odr/pages/search.tsx
1. changed loading page text
2. resolved texatarea issue in dispute form
> feat: resolved textarea field in dispute form

- apps/odr/pages/checkoutPage.tsx
1. fixed button position on checkout page
> Feat UI bug fixes

- apps/dsep/components/header/index.tsx
- apps/dsep/components/jobDetails/JobDetailsPage.tsx
- apps/dsep/pages/jobDetails.tsx
- apps/dsep/pages/jobSearch.tsx
https://fide-official.atlassian.net/browse/DUB-282
> feat: fixed issue in job apply title

- apps/odr/components/detailsCard/ConsentFillingDetails.tsx
- apps/odr/locales/en.ts
https://fide-official.atlassian.net/browse/ODR-84
wrong text on additional information page
> feat: wrong text on additional information page

- apps/industry_4.0/components/header/header.module.css
- apps/industry_4.0/components/header/index.tsx
- apps/industry_4.0/components/productCard/product-card-renderer.tsx
- apps/industry_4.0/components/productDetails/index.tsx
- apps/industry_4.0/components/signIn/SignIn.tsx
- apps/industry_4.0/pages/checkoutPage.tsx
- apps/industry_4.0/pages/invoiceDetails.tsx
- apps/industry_4.0/pages/orderConfirmation.tsx
- apps/industry_4.0/pages/orderDetails.tsx
- apps/industry_4.0/pages/orderHistory.tsx
- apps/industry_4.0/pages/search.tsx
- apps/industry_4.0/pages/signUp.tsx
- packages/becknified-components/src/components/prouct-description/product-description.tsx
1. Added Toast on signUp and SignIn page
2. Added Validation On SignUp Page
3. Changes Some Header Text
> feat: ui changes done

- apps/industry_4.0/components/header/index.tsx
- apps/industry_4.0/components/productCard/product-card-renderer.tsx
1. on Sign up Page title is not in sync with figma ,so i have changed as per figma
2. on Add Assembly Details  Page title is wrong . so i have added proper title 
3. Industry 4.0-According to Figma, the Home icon is not present on the Sign-Up page.(https://fide-official.atlassian.net/browse/BIN-59)
> Fix ind4.0 bugs

- apps/industry_4.0/components/starRating/StarRating.tsx
- apps/industry_4.0/locales/en.ts
- apps/industry_4.0/pages/feedback.tsx
- apps/industry_4.0/pages/orderDetails.tsx
> feat: implemented feedback page

- apps/industry_4.0/pages/checkoutPage.tsx
- apps/industry_4.0/pages/orderDetails.tsx
- apps/industry_4.0/pages/updateShippingDetails.tsx
- apps/industry_4.0/types/status.types.ts
fixes issue , for the order details page; when transitioning from the order details page to the homePage, the order history page wasn't functioning correctly because local storage was cleared
> fix: orderDetails page fixes

- apps/odr/components/detailsCard/ConsentForm.tsx
https://fide-official.atlassian.net/browse/ODR-69
ODR - "Cancel" Button not working in "Fill Consent Form"
> fix: cancel button not working in fill consent form

- apps/industry_4.0/pages/updateShippingDetails.tsx
fix: solved build time error, due to local storage
> fix: solved build time error, due to local storage

- apps/dsep/pages/jobApply.tsx
added error in catch block and added toast
> feat: added error in catch block and added toast

- apps/dsep/pages/applyScholarship.tsx
added toast to handle error in scholarship flow
> fix: added toast to handle error in scholarship flow

- apps/dsep/components/productCard/product-card-renderer.tsx
- apps/dsep/components/productDetails/index.tsx
- apps/dsep/components/productList/ProductList.tsx
- apps/dsep/pages/product.tsx
- apps/dsep/types/search.types.ts
- packages/becknified-components/src/components/product-price/ProductPrice.types.ts
- packages/becknified-components/src/components/product-price/product-price.tsx
- packages/becknified-components/src/components/prouct-description/product-description.tsx
* create product description page ui with bb
* added the universal formatter logic in product price component in building block
> feat: courses product description page

- apps/retail/components/header/CartIcon.tsx
- apps/retail/components/header/index.tsx
- apps/retail/components/layout/Layout.tsx
- apps/retail/hooks/useRequest.tsx
- apps/retail/lib/types/cart.ts
- apps/retail/lib/types/index.ts
- apps/retail/lib/types/localstorage.ts
- apps/retail/package.json
- apps/retail/pages/_app.tsx
- apps/retail/pages/cart.tsx
- apps/retail/pages/product.tsx
- apps/retail/pages/search.tsx
- apps/retail/services/Users.ts
- apps/retail/services/becknApi.ts
- apps/retail/store/index.ts
- apps/retail/tsconfig.json
- apps/retail/types/search.types.ts
- apps/retail/utilities/index.ts
- apps/retail/utilities/localstorage.ts
- apps/retail/utilities/search-results.utils.ts
- packages/becknified-components/src/components/product-card/product-card.tsx
- packages/becknified-components/src/components/product-card/product-card.types.ts
- yarn.lock
1. migrated search to 1.1.0
2. migrated cart to 1.1.0
3. migrated product-details to 1.1.0
> feat: integrating gcl

- apps/dsep/lib/types/confirm.types.ts
- apps/dsep/locales/en.ts
- apps/dsep/pages/checkoutPage.tsx
- apps/dsep/pages/orderConfirmation.tsx
- apps/dsep/utilities/checkout-utils.ts
- apps/dsep/utilities/confirm-utils.ts
- packages/becknified-components/src/components/checkout/payment-details.tsx
* built confirm page ui with building blocks
* integrated confirm api
* completed high and low level data mapping on the page
> feat: course confirm changes

- apps/dsep/.env
- apps/dsep/components/orderDetails/ViewMoreOrderModal.tsx
- apps/dsep/lib/types/status.types.ts
- apps/dsep/locales/en.ts
- apps/dsep/pages/orderDetails.tsx
- apps/dsep/pages/search.tsx
- apps/dsep/utilities/confirm-utils.ts
- apps/dsep/utilities/orderDetails-utils.ts
* Created order details ui with building blocks
* integrated gcl api
* completed low level data mapping
* completed high level data mapping
> feat: course status work

- apps/retail/lib/types/cart.ts
- apps/retail/pages/cart.tsx
- apps/retail/pages/checkout.tsx
- apps/retail/pages/index.tsx
- packages/becknified-components/src/components/cart/cart.types.ts
- packages/becknified-components/src/components/cart/order-summary.module.css
- packages/becknified-components/src/components/checkout/checkout-item-details.tsx
- packages/becknified-components/src/components/checkout/checkout.tsx
- packages/becknified-components/src/components/checkout/checkout.types.ts
- packages/becknified-components/src/components/product-Cta/product-cta.tsx
- packages/becknified-components/src/components/product-card/product-card.tsx
- packages/becknified-components/src/components/product-price/product-price.tsx
1. Disable proceed to checkout if checkbox is unchecked 
2.  Search for anything on search page placeholder 
3. Currency check on every page
4. Some UI issue
> fix: cuurency issuue and some ui issue

- apps/dsep/components/jobSearch/JobSearch.tsx
- apps/dsep/components/jobSearch/JobsSearch.types.ts
- apps/dsep/components/jobSearch/job-card-renderer.tsx
- apps/dsep/locales/en.ts
- apps/dsep/pages/jobSearch.tsx
- apps/dsep/types/search.types.ts
- apps/dsep/utilities/search-utils.ts
* created ui using building blocks
* integrated generic client layer api
* added the data mapping in higher and lower level components
* defined some types related to it
> feat: job search implementation

- apps/dsep/components/jobDetails/JobDetails.types.ts
- apps/dsep/components/jobDetails/JobDetailsPage.tsx
- apps/dsep/pages/jobDetails.tsx
- apps/dsep/pages/jobSearch.tsx
* job details ui with building block
* completed the data mapping on the page
* also refactored the ui layout
> feat: job details page

- apps/dsep/components/detailsCard/ShippingForm.module.css
- apps/dsep/lib/types/select.types.ts
- apps/dsep/locales/en.ts
- apps/dsep/pages/applicationSent.tsx
- apps/dsep/pages/jobApply.tsx
- apps/dsep/pages/orderConfirmation.tsx
- apps/dsep/utilities/checkout-utils.ts
- apps/dsep/utilities/job-apply-utils.ts
- apps/industry_4.0/pages/orderConfirmation.tsx
- apps/retail/pages/orderConfirmation.tsx
- packages/becknified-components/src/pages/confirmation-page/confirmation-page.tsx
- packages/becknified-components/src/pages/confirmation-page/confirmation-page.types.ts
* Integrated strapi apis like document fetch, profile fetch etc
* build application ui with building blocks
* integrated select api with jobs
* integrated init api with jobs
* integrated confirm api with jobs
* completed data mapping with low level and high level components
* did some code fixes in order confirmation compponent in building block
> feat: job application and confirmation

- apps/dsep/components/scholarship/scholarshipCard/scholarshipListCard.tsx
- apps/dsep/locales/en.ts
- apps/dsep/pages/scholarshipSearchPage.tsx
- apps/dsep/pages/search.tsx
- apps/dsep/utilities/search-utils.ts
* Implemented scholarship search page ui with building blocks
* integreated the search api with gcl
* completed the data mapping at both low level and high level components
* handled the error case
> feat: scholarship search page

- apps/dsep/components/scholarship/scholarshipCard/scholarshipListCard.tsx
- apps/dsep/components/scholarship/scholarshipDetails/ScholarshipDetails.tsx
- apps/dsep/pages/scholarshipDetailsPage.tsx
* implemented scholarship description page ui with building block
* completed data mapping on both highlevel and low-level components
> feat: scholarship description page

- apps/dsep/components/scholarship/scholarship-apply-utils.ts
- apps/dsep/components/uploadFile/UploadFile.tsx
- apps/dsep/lib/types/select.types.ts
- apps/dsep/pages/applyScholarship.tsx
* created scholarship application ui with building blocks
* integrated init with gcl
* completed high and low level data mapping
> feat: scholarhship application

- apps/dsep/pages/scholarshipConfirmationPage.tsx
* implented job application confirmation ui with building block
> feat: job confirmation ui

- apps/dsep/components/scholarship/scholarshipCard/ScholarshipCard.tsx
- apps/dsep/lib/types/order-history.types.ts
- apps/dsep/locales/en.ts
- apps/dsep/pages/myScholarship.tsx
* created scholarship history ui with building block
* changed the data mapping from old schema to new schema according to the gcl
* added the required types
* integrated the approve scholarship with the course cart
> feat: scholarship history and its integration with course

- apps/dsep/components/orderHistory/MyLearing.tsx
- apps/dsep/lib/types/confirm.types.ts
- apps/dsep/pages/myLearningOrderHistory.tsx
- apps/dsep/pages/orderConfirmation.tsx
- apps/dsep/utilities/confirm-utils.ts
* created course history page ui with building blocks
* created new data mapping with the higher and lower level components with the gcl
* implemented the post order flow with the new schema of confirm response of gcl
> feat: course history implementation

- apps/dsep/components/orderHistory/MyJob.tsx
- apps/dsep/pages/applyJobsPrefilled.tsx
- apps/dsep/pages/myJobsOrderHistory.tsx
* created jobs order history page with bb
* changed the data mapping all over the components
* implemented prefilled job details page with bb
* changed the data mapping on prefilled job details page
> feat: implementing jobs order history

- apps/dsep/.env
- apps/dsep/components/productCard/product-card-renderer.tsx
- apps/dsep/pages/myLearningOrderHistory.tsx
- apps/dsep/types/search.types.ts
- apps/dsep/utilities/search-utils.ts
* initially course duration and course url was not coming in backend
* now its coming from backend, have done the mapping for it in both product list and course history page
> feat: course duration and course url fix

- apps/retail/components/header/index.tsx
- apps/retail/components/topSheet/TopSheet.module.css
- apps/retail/components/topSheet/TopSheet.tsx
- apps/retail/pages/index.tsx
- apps/retail/pages/orderConfirmation.tsx
- apps/retail/pages/signUp.tsx
- apps/retail/pages/signin.tsx
- apps/retail/styles/globals.css
- yarn.lock
fixed extra padding from signIn page
fixed extra padding from order confirmation page
and fixed bottom header location responsiveness on homepage
> fix: fixed extra padding and bottom header responsivness on homepage

- apps/retail/components/card/Card.tsx
- apps/retail/components/header/index.tsx
- apps/retail/locales/en.ts
- apps/retail/pages/cart.tsx
- apps/retail/pages/checkout.tsx
- apps/retail/pages/paymentMode.tsx
- packages/becknified-components/src/components/product-Cta/product-cta.tsx
1. 1. QA for Retail migration for Product Page[#623](https://github.com/beckn/beckn-ui-workspace/issues/623)
2. QA for Retail migration for Cart Page[#624](https://github.com/beckn/beckn-ui-workspace/issues/624)
3. QA for Retail migration for Checkout[#625](https://github.com/beckn/beckn-ui-workspace/issues/625)
4. QA for Retail migration for Payment Page[#626](https://github.com/beckn/beckn-ui-workspace/issues/626)
> fix: retail app bottom header and other bugs

- apps/retail/components/header/index.tsx
- apps/retail/pages/cart.tsx
- apps/retail/pages/checkout.tsx
- apps/retail/pages/orderConfirmation.tsx
- packages/becknified-components/src/components/checkout/checkout.types.ts
- packages/becknified-components/src/components/checkout/shipping-section.tsx
- packages/becknified-components/src/components/product-Cta/product-cta.tsx
1. Kuza One - On product details page Direction of + and - are change[#639](https://github.com/beckn/beckn-ui-workspace/issues/639)
2.Kuza One - Text Color is different on checkout flow[#640](https://github.com/beckn/beckn-ui-workspace/issues/640)
3.Kuza One - Heading is mismatch on create profile page[#644](https://github.com/beckn/beckn-ui-workspace/issues/644)
4.Kuza One - Success message is not match with figma[#651](https://github.com/beckn/beckn-ui-workspace/issues/651)
5.Kuza One - Button name is different onOrder success page[#652](https://github.com/beckn/beckn-ui-workspace/issues/652)
6.Kuza One - On cart page, Button name id change[#656](https://github.com/beckn/beckn-ui-workspace/issues/656)
7.Kuza One - Order cancelled page, not synch with …
> fix: fixes all bugs assigned by kunal

- apps/retail/pages/cart.tsx
- apps/tourismV1.1/components/button/Button.tsx
- apps/tourismV1.1/components/filter/Filter.tsx
- apps/tourismV1.1/pages/search.tsx
- apps/tourismV1.1/styles/globals.css
- packages/becknified-components/src/components/product-card/product-card.tsx
fixed: https://github.com/beckn/beckn-ui-workspace/issues/858
fixed: https://github.com/beckn/beckn-ui-workspace/issues/857
fixed: https://github.com/beckn/beckn-ui-workspace/issues/856
> fix: himalaya torism and retail bugs

- apps/odr-v2/components/x-input/AddSection.module.css
- apps/odr-v2/components/x-input/AddSection.tsx
- apps/odr-v2/locales/en.ts
- apps/odr-v2/pages/checkout.tsx
> Fix: disabled checkout info sections

- apps/odr-v2/components/checkout/checkout.utils.tsx
- apps/odr-v2/components/x-input/AddSection.module.css
- apps/odr-v2/components/x-input/AddSection.tsx
- apps/odr-v2/pages/checkout.tsx
- packages/becknified-components/src/components/checkout/checkout.types.ts
- packages/becknified-components/src/components/checkout/details-card.tsx
- packages/becknified-components/src/components/checkout/shipping-section.tsx
- packages/becknified-components/src/components/detail-card/detail-card.tsx
- packages/molecules/src/components/bottom-modal/bottom-modal.tsx
> Fix: ODR - checkout form details

- apps/dsep/pages/orderDetails.tsx
added toast, if updateResponse is success
> fix: added toast for  edit billing details

- apps/odr-v2/components/layout/Layout.tsx
- apps/odr-v2/components/signIn/SignIn.tsx
- apps/odr-v2/locales/en.ts
- apps/odr-v2/pages/checkout.tsx
- apps/odr-v2/pages/feedback.tsx
- apps/odr-v2/pages/index.tsx
- apps/odr-v2/pages/orderConfirmation.tsx
- apps/odr-v2/pages/orderDetails.tsx
- apps/odr-v2/pages/profile.tsx
- apps/odr-v2/pages/search.tsx
- apps/odr-v2/pages/signUp.tsx
- apps/odr-v2/pages/updateShippingDetails.tsx
- apps/odr-v2/services/api.ts
- apps/odr-v2/services/axios.ts
- apps/odr-v2/services/becknApi.ts
- apps/odr-v2/store/index.ts
- apps/odr-v2/store/ui-feedback-slice.ts
- apps/retail/components/signIn/SignIn.tsx
- apps/retail/pages/feedback.tsx
> feat: added building block toast component in odr app

- apps/dsnp-v2/components/layout/Layout.tsx
- apps/dsnp-v2/components/signIn/SignIn.tsx
- apps/dsnp-v2/components/signIn/Signin.utils.ts
- apps/dsnp-v2/hooks/useRequest.tsx
- apps/dsnp-v2/locales/en.ts
- apps/dsnp-v2/pages/_app.tsx
- apps/dsnp-v2/pages/checkout.tsx
- apps/dsnp-v2/pages/feedback.tsx
- apps/dsnp-v2/pages/orderConfirmation.tsx
- apps/dsnp-v2/pages/orderDetails.tsx
- apps/dsnp-v2/pages/product.tsx
- apps/dsnp-v2/pages/profile.tsx
- apps/dsnp-v2/pages/search.tsx
- apps/dsnp-v2/pages/signUp.tsx
- apps/dsnp-v2/pages/updateShippingDetails.tsx
- apps/dsnp-v2/services/api.ts
- apps/dsnp-v2/services/axios.ts
- apps/dsnp-v2/services/becknApi.ts
- apps/dsnp-v2/store/index.ts
- apps/dsnp-v2/store/ui-feedback-slice.ts
- apps/dsnp-v2/utilities/auth.ts
2. added axios interceptor across dsnp app
> feat: 1. added toast across the dsnp application

- apps/dsep/components/applyJob/apply-job.tsx
- apps/dsep/components/applyScholarship/apply-scholarship.tsx
- apps/dsep/components/layout/Layout.tsx
- apps/dsep/components/productDetails/index.tsx
- apps/dsep/components/signIn/SignIn.tsx
- apps/dsep/components/uploadFile/UploadFile.tsx
- apps/dsep/hooks/useRequest.tsx
- apps/dsep/locales/en.ts
- apps/dsep/pages/_app.tsx
- apps/dsep/pages/api/users/register.ts
- apps/dsep/pages/applyJobsPrefilled.tsx
- apps/dsep/pages/applyScholarship.tsx
- apps/dsep/pages/cart.tsx
- apps/dsep/pages/checkoutPage.tsx
- apps/dsep/pages/createProfile.tsx
- apps/dsep/pages/feedback.tsx
- apps/dsep/pages/homePage.tsx
- apps/dsep/pages/index.tsx
- apps/dsep/pages/jobApply.tsx
- apps/dsep/pages/jobSearch.tsx
- apps/dsep/pages/login.tsx
- apps/dsep/pages/orderConfirmation.tsx
- apps/dsep/pages/orderDetails.tsx
- apps/dsep/pages/scholarshipSearchPage.tsx
- apps/dsep/pages/search.tsx
- apps/dsep/pages/signUp.tsx
- apps/dsep/services/axios.ts
- apps/dsep/store/index.ts
- apps/dsep/store/ui-feedback-slice.ts
- apps/dsep/utilities/checkout-utils.ts
2. added axios interceptor across dsep app
> fix: 1. added toast across the dsep application

- packages/common/lib/config.ts
- packages/common/lib/types/beckn/confirm.types.ts
- packages/common/lib/types/beckn/index.ts
- packages/common/lib/types/beckn/init.types.ts
- packages/common/lib/types/beckn/order-details.types.ts
- packages/common/lib/types/beckn/order-history.types.ts
- packages/common/lib/types/beckn/search.types.ts
- packages/common/lib/types/beckn/select.types.ts
- packages/common/lib/types/beckn/status.types.ts
- packages/common/lib/types/cart.ts
- packages/common/lib/types/common.ts
- packages/common/lib/types/discovery.ts
- packages/common/lib/types/general.ts
- packages/common/lib/types/geoLocationSearchPage.ts
- packages/common/lib/types/index.ts
- packages/common/lib/types/localstorage.ts
- packages/common/lib/types/order.ts
- packages/common/lib/types/payment.ts
- packages/common/lib/types/products.ts
- packages/common/lib/types/search.ts
- packages/common/lib/types/settingBox.ts
- packages/common/src/store/cart-slice.ts
- packages/common/src/store/discovery-slice.ts
- packages/common/src/store/geoMapLocationSearch-slice.ts
- added common models in single file
- added model specific to beckn & extend models from common
- added model specific to component level & extend models from common
> fix: modified code in common to add lib/types

- apps/retail/components/signIn/SignIn.tsx
- apps/retail/locales/en.ts
- apps/retail/pages/profile.tsx
- apps/retail/pages/signUp.tsx
- apps/retail/utilities/form-utils.ts
1. until there is error in sign in page button should be disabled
2. flat number and street fields are optional you can proceed without this field
> fix: validation on sign in and profile page

- apps/OSC/components/signIn/SignIn.tsx
- apps/OSC/locales/en.ts
- apps/OSC/locales/fa.ts
- apps/OSC/pages/profile.tsx
- apps/OSC/pages/signUp.tsx
- apps/OSC/utilities/form-utils.ts
1. until there is error in sign in and sign up page button should be disabled
2. flat number and street fields are optional you can proceed without this field
3. added usememo for function
> fix: added validation on sign and profile page

- apps/odr-v2/components/signIn/SignIn.tsx
- apps/odr-v2/locales/en.ts
- apps/odr-v2/pages/profile.tsx
- apps/odr-v2/pages/signUp.tsx
- apps/odr-v2/utilities/form-utils.ts
1. until there is error in sign in and sign up page button should be disabled
2. flat number and street fields are optional you can proceed without this field
3. added usememo for function
> fix: added validation on sign in and profile page

- apps/industry_4.0/next.config.js
- apps/industry_4.0/services/axios.ts
- making use of common services
- modified next config file in transpilePackages
> fix: modified code to use common packages in industry

- apps/dsep/next.config.js
- apps/dsep/services/axios.ts
- apps/dsep/store/index.ts
- apps/dsep/tsconfig.json
- making use of common services
- modified tsconfig to add absolute path config
- modified next config file in transpilePackages
> fix: modified code to use common packages in dsep

- packages/common/lib/types/general.ts
- packages/common/src/utils/checkout-utils.ts
- packages/common/src/utils/confirm-utils.ts
- packages/common/src/utils/currency-format.ts
- packages/common/src/utils/form-utils.ts
- packages/common/src/utils/general.ts
- packages/common/src/utils/index.ts
- packages/common/src/utils/localstorage.ts
- packages/common/src/utils/payload.ts
- packages/common/src/utils/search-utils.ts
1. Added utils section inside the common package
2. Segregated them further based on context
3. Deleted un-needed utils or files
> feat: common utils

- apps/OSC/pages/profile.tsx
- apps/dsnp-v2/pages/profile.tsx
- apps/industry_4.0/components/header/index.tsx
- apps/industry_4.0/pages/profile.tsx
- apps/odr-v2/pages/profile.tsx
- apps/retail/pages/profile.tsx
replaced fetch by axios in retail and industry
> fix: fixed undefined in profile input field

- apps/OSC/locales/en.ts
- apps/OSC/locales/fa.ts
- apps/OSC/pages/feedback.tsx
- apps/OSC/pages/updateShippingDetails.tsx
- apps/OSC/utilities/checkout-utils.ts
- apps/dsnp-v2/pages/updateShippingDetails.tsx
- apps/dsnp-v2/utilities/checkout-utils.ts
- apps/odr-v2/pages/updateShippingDetails.tsx
- apps/retail/pages/updateShippingDetails.tsx
- apps/retail/utilities/checkout-utils.ts
- apps/tourismV1.1/pages/feedback.tsx
- apps/tourismV1.1/pages/updateShippingDetails.tsx
- apps/tourismV1.1/utilities/checkout-utils.ts
- packages/becknified-components/src/components/checkout/shipping-form.tsx
1. added toast on feedback page if user rating successfully submitted
2. if Pincode is invalid update api call should not made and show user toast for invalid pincode
> fix: added toast on feedback page and validation on update shipping details page

- apps/retail/pages/orderConfirmation.tsx
- cypress/e2e/retail/orderConfirmation.cy.ts
- cypress/e2e/retail/paymentMode.cy.ts
- cypress/fixtures/confirmPage/confirmRespons.json
- cypress/support/commands.ts
- packages/becknified-components/src/pages/confirmation-page/confirmation-page.tsx
- packages/common/src/components/paymentDetailsCard/PaymentDetailsCard.tsx
- packages/common/src/components/paymentDetailsCard/PaymentDetailsCard.types.ts
- packages/common/src/components/paymentMethodSelection/paymentMethodSelection.tsx
- shared/dataTestIds.ts
1. unit test cases for payment page
2. unit test cases for order confirmation page
> feat: cypress test cases

- apps/retail/pages/orderDetails.tsx
- packages/becknified-components/src/components/checkout/shipping-section.tsx
- packages/common/src/components/cartIconWithCount/cartIconWithCount.tsx
- packages/common/src/components/paymentDetailsCard/PaymentDetailsCard.tsx
- packages/common/src/components/searchBar/searchBar.tsx
- packages/common/src/components/topHeader/topHeader.tsx
- packages/common/src/components/topSheet/topSheet.tsx
1. added cursor pointer when user hover various interactive elements
> feat(RETAIL): added cursor pointer

- apps/odr-v2/pages/index.tsx
- apps/odr-v2/pages/search.tsx
- packages/common/src/components/homePageContent/homePageContent.tsx
- packages/common/src/components/homePageContent/homePageContent.types.ts
1. added topsheet from common packages
2. added homepage schema using common packages
> feat(ODR): implement homepage in ODR using common packages

- apps/taxi-bpp-v2/components/layout/Layout.tsx
- apps/taxi-bpp-v2/pages/index.tsx
- apps/taxi-bpp-v2/services/RiderService.ts
- apps/taxi-bpp-v2/services/UserService.ts
- apps/taxi-bpp-v2/services/api.ts
- apps/taxi-bpp-v2/store/auth-slice.ts
- apps/taxi-bpp-v2/store/index.ts
- apps/taxi-bpp-v2/store/rider-slice.ts
- apps/taxi-bpp-v2/utilities/geoLocation-utils.ts
- packages/common/src/components/topSheet/topSheet.tsx
- added configurn for redux-toolkit for api calls
- added configrn for redux store
- integration of apii
> feat(taxi-bpp): integrate online/offline api and store config

- apps/odr-v2/pages/search.tsx
- apps/retail/pages/orderHistory.tsx
- cypress/e2e/odr/homePage.cy.ts
- cypress/e2e/retail/cart.cy.ts
- packages/becknified-components/src/components/checkout/shipping-section.tsx
- packages/becknified-components/src/components/product-Cta/product-cta.tsx
- packages/common/src/components/homePageContent/homePageContent.tsx
- packages/common/src/components/searchAndDiscover/searchAndDiscover.tsx
- packages/common/src/components/searchAndDiscover/searchAndDiscover.types.ts
- packages/common/src/components/searchBar/searchBar.tsx
- packages/common/src/components/searchBar/searchBar.types.ts
- packages/common/src/components/subHeader/subHeader.tsx
- shared/dataTestIds.ts
1. added test cases for homepage
2. as per comment added generic name for search bar
> feat(ODR): added cypress test cases for homepage

- apps/odr-v2/locales/en.ts
- apps/odr-v2/pages/checkout.tsx
- apps/odr-v2/pages/product.tsx
- cypress/e2e/odr/product.cy.ts
- cypress/e2e/odr/searchPage.cy.ts
- cypress/fixtures/ODR/searchPage/emptySearchResults.json
- cypress/fixtures/ODR/searchPage/searchResults.json
1. added test cases for search page
2. added test cases for product detail page
> feat(ODR): test cases for ODR

- apps/taxi-bpp-v2/components/Map/Map.tsx
- apps/taxi-bpp-v2/components/ride-summary/rideSummary.tsx
- apps/taxi-bpp-v2/lib/types/profile.ts
- apps/taxi-bpp-v2/lib/types/rideDetails.ts
- apps/taxi-bpp-v2/pages/index.tsx
- apps/taxi-bpp-v2/pages/profile.tsx
- apps/taxi-bpp-v2/services/RiderService.ts
- update driver location continueosuly
- integrate update driver location API
> fix(driver-bpp): modified code to fix navigation in map

- apps/odr-v2/components/x-input/AddSection.tsx
- apps/odr-v2/components/x-input/DyForm.tsx
- apps/odr-v2/pages/checkout.tsx
- apps/odr-v2/pages/orderConfirmation.tsx
- cypress/e2e/odr/checkout.cy.ts
- cypress/e2e/odr/orderConfirmation.cy.ts
- cypress/e2e/retail/orderConfirmation.cy.ts
- cypress/fixtures/ODR/checkoutPage/consentFormResponse.json
- cypress/fixtures/ODR/checkoutPage/disputeSubmitFormResponse.json
- cypress/fixtures/ODR/checkoutPage/initResponse.ts
- cypress/fixtures/ODR/checkoutPage/selectResponse.json
- cypress/fixtures/ODR/checkoutPage/userDetails.ts
- cypress/fixtures/ODR/orderConfirmation/confirmResponse.ts
- cypress/fixtures/ODR/orderConfirmation/orderResponse.ts
- cypress/support/commands.ts
- shared/dataTestIds.ts
1. added Test cases for checkout page
2. added test cases for order confirmation page
> feat(ODR): added Test cases for ODR

- apps/odr-v2/components/orderDetailComponents/Shipping.tsx
- apps/odr-v2/components/starRating/StarRating.tsx
- apps/odr-v2/pages/feedback.tsx
- apps/odr-v2/pages/orderDetails.tsx
- apps/odr-v2/pages/updateShippingDetails.tsx
- apps/retail/pages/orderHistory.tsx
- cypress/e2e/odr/feedback.cy.ts
- cypress/e2e/odr/orderDetails.cy.ts
- cypress/e2e/retail/checkout.cy.ts
- cypress/e2e/retail/feedback.cy.ts
- cypress/e2e/retail/homePage.cy.ts
- cypress/e2e/retail/orderConfirmation.cy.ts
- cypress/e2e/retail/orderDetails.cy.ts
- cypress/e2e/retail/orderHistory.cy.ts
- cypress/e2e/retail/paymentMode.cy.ts
- cypress/e2e/retail/product.cy.ts
- cypress/e2e/retail/profile.cy.ts
- cypress/e2e/retail/searchPage.cy.ts
- cypress/fixtures/ODR/checkoutPage/userDetails.ts
- cypress/fixtures/ODR/feedback/ratingResponse.json
- cypress/fixtures/ODR/orderDetails/statusResponse.ts
- cypress/fixtures/ODR/orderDetails/supportResponse.json
- cypress/fixtures/ODR/orderDetails/trackResponse.json
- cypress/fixtures/ODR/orderDetails/updateShippingDetails.ts
- cypress/fixtures/orderHistory/emptyOrderResponse.json
- shared/dataTestIds.ts
1. added test cases for order details page in odr app
2. added test cases for feedback page in odr app
3. refactor retail app all test cases
> feat(ODR): added test cases for odr app

- apps/odr-v2/components/header/constants/index.ts
- apps/odr-v2/components/orderHistory/emptyOrder.tsx
- apps/odr-v2/pages/orderHistory.tsx
- apps/odr-v2/pages/profile.tsx
- cypress/e2e/odr/orderHistory.cy.ts
- cypress/e2e/odr/profile.cy.ts
- cypress/fixtures/ODR/orderHistory/emptyOrderResponse.json
- cypress/fixtures/ODR/orderHistory/orderResponse.json
- cypress/fixtures/ODR/profile/profileDetails.ts
- cypress/fixtures/ODR/profile/profileResponse.json
- shared/dataTestIds.ts
1. added test cases for profile page
2. added test cases for order history page
> feat(ODR): added test cases

- apps/mobility-bap/components/alertModal/alertModal.tsx
- apps/mobility-bap/components/bottomModalRenderer/bottomModalRenderer.tsx
- apps/mobility-bap/components/header/constants/index.ts
- apps/mobility-bap/components/pickUpDropOff/pickUpDropOffContainer.tsx
- apps/mobility-bap/components/quarantineZoneMap/quarantineZoneMap.tsx
- apps/mobility-bap/pages/geofence.tsx
- apps/mobility-bap/pages/quarantineZone.tsx
- apps/mobility-bap/public/images/Indicator.svg
- apps/mobility-bap/store/index.ts
- apps/mobility-bap/store/policy-slice.ts
- apps/mobility-bap/utilities/general.ts
- get policy by id api integration
- get violation check api integration
- ui for alert modal
- ui for rendering geofence lat long
> feat(mobility-bap): implement & integrate api for policy alert modal

- apps/mobility-bap/components/ride-details/RideDetails.tsx
- apps/mobility-bap/components/searchRideForm/SearchRideForm.tsx
- apps/mobility-bap/lib/config.ts
- apps/mobility-bap/lib/types/user.ts
- apps/mobility-bap/pages/index.tsx
- apps/mobility-bap/pages/searchRide.tsx
- apps/mobility-bap/store/user-slice.ts
- apps/mobility-bap/utilities/general.ts
- added logic for getting experience type
- set the current location as per the experience center type
> feat(mobility-bap): implemenation for smartCity, gambia, paris flow

- apps/mobility-bap/components/pickUpDropOff/pickUpDropOffContainer.tsx
- apps/mobility-bap/components/ride-details/RideDetails.tsx
- apps/mobility-bap/components/ride-details/rideDetailsCardContainer.tsx
- apps/mobility-bap/components/searchRideForm/SearchRideForm.tsx
- apps/mobility-bap/pages/searchRide.tsx
- apps/mobility-bap/utilities/general.ts
- apps/taxi-bpp-v2/pages/index.tsx
- apps/taxi-bpp-v2/pages/myRides.tsx
- apps/taxi-bpp-v2/utilities/ride-utils.ts
- apps/taxi-bpp-v2/utilities/rideSummary-utils.ts
- added toaster for status update call
> fix(mobility-bap): fixed issues related to fare mismtached

- apps/mobility-bap/components/bottomModalRenderer/bottomModalRenderer.tsx
- apps/mobility-bap/components/pickUpDropOff/pickUpDropOffContainer.tsx
- apps/mobility-bap/components/ride-details/RideDetails.tsx
- apps/mobility-bap/components/ride-details/rideDetailsCardContainer.tsx
- apps/mobility-bap/components/searchRideForm/SearchRideForm.tsx
- apps/mobility-bap/lib/types/user.ts
- apps/mobility-bap/pages/index.tsx
- apps/mobility-bap/pages/searchRide.tsx
- apps/mobility-bap/store/user-slice.ts
- apps/taxi-bpp-v2/components/ride-summary/rideSummary.tsx
- apps/taxi-bpp-v2/components/ride-summary/rideSummaryHeader.tsx
- apps/taxi-bpp-v2/lib/config.ts
- apps/taxi-bpp-v2/lib/types/ride.ts
- apps/taxi-bpp-v2/lib/types/rideDetails.ts
- apps/taxi-bpp-v2/pages/index.tsx
- apps/taxi-bpp-v2/pages/myRides.tsx
- apps/taxi-bpp-v2/utilities/ride-utils.ts
- apps/taxi-bpp-v2/utilities/rideSummary-utils.ts
- packages/common/lib/types/geoLocationSearchPage.ts
- packages/common/src/components/geoLocationInput/GeoLocationInputList.tsx
- packages/common/src/hooks/useGeolocation.tsx
- packages/common/src/store/geoMapLocationSearch-slice.ts
- updated code in geoloation input component
- fixed re-redering of toast in status call
> fix(mobility-bap-bpp): fixed issues related to currency & geolocation

- apps/industry_4.0/components/header/SearchBar.tsx
- apps/industry_4.0/components/layout/Layout.tsx
- apps/industry_4.0/components/productCard/product-card-renderer.tsx
- apps/industry_4.0/locales/en.ts
- apps/industry_4.0/pages/index.tsx
- apps/industry_4.0/pages/search.tsx
- cypress/e2e/industry4.0/auth.cy.ts
- cypress/e2e/industry4.0/homePage.cy.ts
- cypress/e2e/industry4.0/searchPage.cy.ts
- cypress/fixtures/INDUSTRY4.0/searchPage/emptySearchResults.json
- cypress/fixtures/INDUSTRY4.0/searchPage/searchResults.json
- packages/becknified-components/src/components/search-input/search-input.tsx
- shared/dataTestIds.ts
1. added test cases for auth page
2. added test cases for home page
3. added test cases for search page
> feat(industry4.0): test cases for industry4.0

- apps/industry_4.0/components/productDetails/index.tsx
- apps/industry_4.0/pages/assemblyDetails.tsx
- apps/industry_4.0/pages/checkoutPage.tsx
- cypress/e2e/industry4.0/assemblyDetails.cy.ts
- cypress/e2e/industry4.0/checkoutPage.cy.ts
- cypress/e2e/industry4.0/product.cy.ts
- cypress/fixtures/INDUSTRY4.0/checkoutPage/initResponse.ts
- cypress/fixtures/INDUSTRY4.0/checkoutPage/selectResponse.json
- cypress/fixtures/INDUSTRY4.0/checkoutPage/userDetails.ts
- cypress/fixtures/INDUSTRY4.0/select/selectResult.json
- cypress/fixtures/INDUSTRY4.0/x-input/x-inputResult.json
- cypress/support/commands.ts
- packages/becknified-components/src/components/product-summary/product-summary.tsx
- shared/dataTestIds.ts
1. added test cases for product page
2. added test cases for assembly details page
3. added test cases for checkout page
> feat(Industry4.0): test cases for industry4.0 app

- apps/tourismV1.1/components/layout/Layout.tsx
- cypress/e2e/Tourism/auth.cy.ts
- cypress/e2e/Tourism/homePage.cy.ts
- packages/common/src/components/geoLocationInput/GeoLocationInput.tsx
- packages/common/src/components/geoLocationInput/GeoLocationInputList.tsx
- shared/dataTestIds.ts
1. added test cases for sign in sign up page
2. added test cases for homepage
> feat(tourism): test cases for tourism app

- apps/tourismV1.1/components/BottomModal/BottomModalScan.tsx
- apps/tourismV1.1/components/orderDetailComponents/Shipping.tsx
- apps/tourismV1.1/components/orderDetailComponents/ViewMoreOrder.tsx
- apps/tourismV1.1/locales/en.ts
- apps/tourismV1.1/pages/checkout.tsx
- apps/tourismV1.1/pages/orderConfirmation.tsx
- apps/tourismV1.1/pages/orderDetails.tsx
- apps/tourismV1.1/pages/product.tsx
- apps/tourismV1.1/pages/updateShippingDetails.tsx
- cypress/e2e/Tourism/checkout.cy.ts
- cypress/e2e/Tourism/orderConfirmation.cy.ts
- cypress/e2e/Tourism/orderDetails.cy.ts
- cypress/e2e/Tourism/paymentMode.cy.ts
- cypress/e2e/Tourism/product.cy.ts
- cypress/e2e/Tourism/searchPage.cy.ts
- cypress/e2e/retail/homePage.cy.ts
- cypress/fixtures/TOURISM/checkoutPage/initResponse.ts
- cypress/fixtures/TOURISM/checkoutPage/selectResponse.json
- cypress/fixtures/TOURISM/checkoutPage/userDetails.ts
- cypress/fixtures/TOURISM/orderConfirmation/confirmResponse.ts
- cypress/fixtures/TOURISM/orderConfirmation/orderResponse.ts
- cypress/fixtures/TOURISM/orderDetails/statusResponse.ts
- cypress/fixtures/TOURISM/orderDetails/supportResponse.json
- cypress/fixtures/TOURISM/orderDetails/trackResponse.json
- cypress/fixtures/TOURISM/orderDetails/updateShippingDetails.ts
- cypress/fixtures/TOURISM/searchPage/emptySearchResults.json
- cypress/fixtures/TOURISM/searchPage/searchResults.json
- cypress/support/commands.ts
- packages/common/src/components/subHeader/subHeader.tsx
- shared/dataTestIds.ts
1. added test cases for search product and checkout page
2. added test cases for payment orderConfirmation and orderdetails page
> feat(tourism): test cases for tourism

- apps/policy-admin/middleware.ts
- apps/policy-admin/pages/signIn.tsx
- apps/policy-admin/services/UserService.ts
- apps/policy-admin/store/auth-slice.ts
Added login api integration for policy-admin
> feat(policy-admin): login api integration

- apps/policy-admin/components/dataTable/dataTable.tsx
- apps/policy-admin/components/viewDetails/viewDetails.tsx
- apps/policy-admin/lib/types/table.ts
- apps/policy-admin/middleware.ts
- apps/policy-admin/pages/resetPassword.tsx
- apps/policy-admin/pages/signIn.tsx
- apps/policy-admin/services/PolicyService.ts
- apps/policy-admin/services/UserService.ts
Created reset password page and integrated apis for reset password, get by id
> feat(policyadmin): created reset password page, api integration

- apps/policy-admin/components/header/constants/index.ts
- apps/policy-admin/components/layout/Layout.tsx
- apps/policy-admin/locales/en.ts
- apps/policy-admin/pages/resetPassword.tsx
- apps/policy-admin/pages/signIn.tsx
1. added eye on off functionality on reset password form
2. changes some text and added in en file
3. replace chakra modal to beckn modal
> fix(policyAdmin): fixed policy admin app bugs

- apps/dsep/components/button/Button.tsx
- apps/dsep/components/cart/CartIcon.tsx
- apps/dsep/components/cart/CartItem.tsx
- apps/dsep/components/cart/EmptyCart.tsx
- apps/dsep/components/cart/OrderSummaryBox.tsx
- apps/dsep/components/header/SearchBar.tsx
- apps/dsep/components/layout/Layout.tsx
- apps/dsep/components/productCard/product-card-renderer.tsx
- apps/dsep/components/productDetails/index.tsx
- apps/dsep/components/productList/ProductList.tsx
- apps/dsep/components/productList/Sort.tsx
- apps/dsep/pages/cart.tsx
- apps/dsep/pages/search.tsx
- cypress/e2e/dsep/auth.cy.ts
- cypress/e2e/dsep/cart.cy.ts
- cypress/e2e/dsep/homePage.cy.ts
- cypress/e2e/dsep/product.cy.ts
- cypress/e2e/dsep/searchPage.cy.ts
- cypress/fixtures/DSEP/cart/selectResult.json
- cypress/fixtures/DSEP/searchPage/emptySearchResults.json
- cypress/fixtures/DSEP/searchPage/searchResults.json
- packages/becknified-components/src/components/star-rating/star-rating.tsx
- shared/dataTestIds.ts
1. added test cases for auth page
2. added test cases for homepage
3. added test cases for search page
4. added test cases for product page
5. added test cases for cart page
> feat(dsep): test cases for dsep

- apps/dsep/components/scholarship/emptyScholarship/EmptyScholarship.tsx
- apps/dsep/pages/scholarshipConfirmationPage.tsx
- cypress/e2e/dsep/myScholarshipPage.cy.ts
- cypress/e2e/dsep/scholarshipApply.cy.ts
- cypress/e2e/dsep/scholarshipConfirmation.cy.ts
- cypress/fixtures/DSEP/MyScholarshipOrder/emptyScholarshipOrderResponse.json
- cypress/fixtures/DSEP/scholarshipApply/initResponse.json
- cypress/fixtures/DSEP/scholarshipApply/profilePopulate.json
- cypress/fixtures/DSEP/scholarshipApply/selectResponse.json
- cypress/fixtures/DSEP/scholarshipApply/x-inputSubmitResponse.json
- cypress/support/commands.ts
- shared/dataTestIds.ts
1. added tewst cases for scholarship apply page
2. added test cases for scholarship confirmation page
3. added test cases for scholarship order page
> feat(dsep): added test cases for dsep

- apps/taxi-bpp-v2/pages/myRides.tsx
- apps/taxi-bpp-v2/pages/profile.tsx
- cypress/e2e/taxi-bpp/myRides.cy.ts
- cypress/e2e/taxi-bpp/profile.cy.ts
- cypress/fixtures/TAXI-BPP/myRides.json
- cypress/fixtures/TAXI-BPP/profile.ts
- shared/dataTestIds.ts
1. test cases for profile page
2. test cases for my rides page
> feat(taxi_bpp): added test cases for taxi bpp

- apps/mobility-bap/components/ride-details/CabDetails.tsx
- apps/mobility-bap/components/ride-details/RideDetails.tsx
- apps/mobility-bap/components/starRating/StarRating.tsx
- apps/mobility-bap/pages/cancelRide.tsx
- cypress/e2e/mobility-bap/cancleRide.cy.ts
- cypress/e2e/mobility-bap/feedback.cy.ts
- cypress/e2e/mobility-bap/rideStared.cy.ts
- cypress/fixtures/mobility-bap/ratingResponse.json
- shared/dataTestIds.ts
1. test cases for ride started modal
2. test cases for feedback page
3. test cases for cancel page
> feat(mobility-app): added Test cases for mobility app

- apps/dragon-foods/components/frequentlyAccessed/FrequentlyAccessed.tsx
- apps/earth-support-initiative/components/frequentlyAccessed/FrequentlyAccessed.tsx
- apps/envirogrowth/components/frequentlyAccessed/FrequentlyAccessed.tsx
- apps/harmoni-aids/components/frequentlyAccessed/FrequentlyAccessed.tsx
- apps/sky-analytics/components/frequentlyAccessed/FrequentlyAccessed.tsx
- apps/state-forest-department/components/frequentlyAccessed/FrequentlyAccessed.tsx
1. have image inside box component for same height
2. have bottom section outside of cardbody for proper alignment
3. made changes across all 6 apps
> fix(climatedata): fix height for cards

- apps/open-spark/components/currentTrade/CurrentTrade.tsx
- apps/open-spark/components/energyPurchaseForm/index.tsx
- apps/open-spark/components/totalEnerguUnit/TotalEnergyUnits.tsx
- apps/open-spark/lib/config.ts
- apps/open-spark/lib/types/dashboard.ts
- apps/open-spark/pages/index.tsx
- apps/open-spark/services/DashboardService.ts
- apps/open-spark/utilities/parsedFormatDate-utils.ts
1. api integration for dashboard with new date payload
2. get and post api integration for trades
> feat(open-spark): api integration for open spark

- apps/dragon-foods/components/frequentlyAccessed/FrequentlyAccessed.tsx
- cypress/e2e/climate-resilience/auth.cy.ts
- cypress/e2e/climate-resilience/homePage.cy.ts
- packages/common/src/components/homePageContent/homePageContent.tsx
- shared/dataTestIds.ts
1. added e2e test cases for auth page
2. added e2e test cases for homepage
> feat(dragon-foods): added cypress e2e test cases for dragon foods app

- cypress/e2e/climate-resilience/Dragon Foods/auth.cy.ts
- cypress/e2e/climate-resilience/Dragon Foods/homePage.cy.ts
- cypress/e2e/climate-resilience/Dragon Foods/searchPage.cy.ts
- cypress/fixtures/Climate-resilience/DRAGON-FOODS/searchPage/emptySearchResults.json
- cypress/fixtures/Climate-resilience/DRAGON-FOODS/searchPage/searchResults.json
1. added test cases for searchpage
> feat(dragon-foods): added test cases for dragon foods app

- apps/open-spark/components/header/constants/index.ts
- apps/open-spark/components/header/index.tsx
- apps/open-spark/pages/dashboard.tsx
- packages/common/src/components/subHeader/subHeader.tsx
- packages/common/src/components/subHeader/subHeader.types.ts
1. on dashboard sell button should be on bottom place
2. on buying prefference there should be profile icon on bottom header
> fix(open-spark): fix open spark bugs on dashboard and subheader icon

- apps/dragon-foods/components/cart/cart-item.tsx
- apps/dragon-foods/pages/product.tsx
- cypress/e2e/climate-resilience/Dragon Foods/cart.cy.ts
- cypress/e2e/climate-resilience/Dragon Foods/checkout.cy.ts
- cypress/e2e/climate-resilience/Dragon Foods/orderConfirmation.cy.ts
- cypress/e2e/climate-resilience/Dragon Foods/orderHistory.cy.ts
- cypress/e2e/climate-resilience/Dragon Foods/paymentMode.cy.ts
- cypress/e2e/climate-resilience/Dragon Foods/product.cy.ts
- cypress/fixtures/Climate-resilience/DRAGON-FOODS/cart/selectResult.json
- cypress/fixtures/Climate-resilience/DRAGON-FOODS/checkoutPage/initResponse.ts
- cypress/fixtures/Climate-resilience/DRAGON-FOODS/checkoutPage/userDetails.ts
- cypress/fixtures/Climate-resilience/DRAGON-FOODS/orderHistory/emptyOrderResponse.json
- cypress/fixtures/Climate-resilience/DRAGON-FOODS/orderHistory/orderResponse.json
- cypress/fixtures/Climate-resilience/DRAGON-FOODS/orderHistory/statusResponse.ts
- shared/dataTestIds.ts
1. added test cases for product page
2. added test cases for Cart page
3. added test cases for checkout page
4. added test cases for payment page
5. added test cases for order confirmation page
6. added test cases for order history page
> feat(open-spark): test cases for open spark app

- apps/envirogrowth/components/frequentlyAccessed/FrequentlyAccessed.tsx
- apps/envirogrowth/pages/product.tsx
- cypress/e2e/forest-conservation/envirogrowth/auth.cy.ts
- cypress/e2e/forest-conservation/envirogrowth/cart.cy.ts
- cypress/e2e/forest-conservation/envirogrowth/checkout.cy.ts
- cypress/e2e/forest-conservation/envirogrowth/homePage.cy.ts
- cypress/e2e/forest-conservation/envirogrowth/orderConfirmation.cy.ts
- cypress/e2e/forest-conservation/envirogrowth/orderHistory.cy.ts
- cypress/e2e/forest-conservation/envirogrowth/paymentMode.cy.ts
- cypress/e2e/forest-conservation/envirogrowth/product.cy.ts
- cypress/e2e/forest-conservation/envirogrowth/searchPage.cy.ts
- cypress/fixtures/forest-conservation/ENVIROGROWTH/cart/selectResult.json
- cypress/fixtures/forest-conservation/ENVIROGROWTH/checkoutPage/initResponse.ts
- cypress/fixtures/forest-conservation/ENVIROGROWTH/checkoutPage/userDetails.ts
- cypress/fixtures/forest-conservation/ENVIROGROWTH/orderHistory/emptyOrderResponse.json
- cypress/fixtures/forest-conservation/ENVIROGROWTH/orderHistory/orderResponse.json
- cypress/fixtures/forest-conservation/ENVIROGROWTH/orderHistory/statusResponse.ts
- cypress/fixtures/forest-conservation/ENVIROGROWTH/searchPage/emptySearchResults.json
- cypress/fixtures/forest-conservation/ENVIROGROWTH/searchPage/searchResults.json
1. added test cases for auth page
2. added test cases for Home page
3. added test cases for search page
4. added test cases for product page
5. added test cases for cart page
6. added test cases for Checkout page
7. added test cases for payment page
8. added test cases for order confirmation page 
9 .added test cases for request history page
> feat(envirogrowth): added test cases for envirogrowth app

- apps/open-spark/pages/tradeDetails.tsx
> fix(open-spark): fixed admin page text based on admin role, it should  be energy bought

- apps/envirogrowth/components/frequentlyAccessed/FrequentlyAccessed.tsx
- apps/state-forest-department/components/cart/cart-item.tsx
- apps/state-forest-department/components/frequentlyAccessed/FrequentlyAccessed.tsx
- cypress/e2e/forest-conservation/stateForestConservation/auth.cy.ts
- cypress/e2e/forest-conservation/stateForestConservation/cart.cy.ts
- cypress/e2e/forest-conservation/stateForestConservation/checkout.cy.ts
- cypress/e2e/forest-conservation/stateForestConservation/homePage.cy.ts
- cypress/e2e/forest-conservation/stateForestConservation/orderConfirmation.cy.ts
- cypress/e2e/forest-conservation/stateForestConservation/orderHistory.cy.ts
- cypress/e2e/forest-conservation/stateForestConservation/paymentMode.cy.ts
- cypress/e2e/forest-conservation/stateForestConservation/product.cy.ts
- cypress/e2e/forest-conservation/stateForestConservation/searchPage.cy.ts
- cypress/fixtures/forest-conservation/StateForestConservation/cart/selectResult.json
- cypress/fixtures/forest-conservation/StateForestConservation/checkoutPage/initResponse.ts
- cypress/fixtures/forest-conservation/StateForestConservation/checkoutPage/userDetails.ts
- cypress/fixtures/forest-conservation/StateForestConservation/orderHistory/emptyOrderResponse.json
- cypress/fixtures/forest-conservation/StateForestConservation/orderHistory/orderResponse.json
- cypress/fixtures/forest-conservation/StateForestConservation/orderHistory/statusResponse.ts
- cypress/fixtures/forest-conservation/StateForestConservation/searchPage/emptySearchResults.json
- cypress/fixtures/forest-conservation/StateForestConservation/searchPage/searchResults.json
1. added test cases for auth page
2. added test cases for Home page
3. added test cases for search page
4. added test cases for product page
5. added test cases for cart page
6. added test cases for Checkout page
7. added test cases for payment page
8. added test cases for order confirmation page 
9 .added test cases for request history page
> feat(state-forest-conservation): added test cases for state forest conservation app

- apps/open-spark/components/documentsRenderer/index.tsx
- apps/open-spark/pages/myCredentials.tsx
1. added cancel button and logic on myCred page
2. align tick icon when file get uploaded
> fix(open-spark): fixed Open Spark-Update "My Credential" Page to Match Figma Design

- apps/open-spark/components/navigationItem/index.tsx
- cypress/e2e/open-spak/profile.cy.ts
- cypress/fixtures/OpenSpark/profile/profile.json
- packages/common/src/components/subHeader/subHeader.tsx
- packages/common/src/components/topSheet/topSheet.tsx
- shared/dataTestIds.ts
1. added context for consumer flow
2. added context fro prosumer flow
> feat(open-spark): cypress E2E test cases for profile page

- apps/open-spark/pages/tradeDetails.tsx
- cypress/e2e/open-spak/trade-details.cy.ts
- cypress/fixtures/OpenSpark/myTrade/consumerSuccessTradeDetails.json
- shared/dataTestIds.ts
1. added test cases for consumer flow
2. added test cases for prosummer flow
> feat(open-spark): test cases for trade details page

- apps/open-spark/components/FormFieldInput/FormFieldInput.tsx
- apps/open-spark/components/wallet/BalanceCard.tsx
- apps/open-spark/components/wallet/TransactionTable.tsx
- apps/open-spark/pages/myFunds.tsx
- apps/open-spark/pages/paymentMode.tsx
- apps/open-spark/pages/withdraw.tsx
1. created a reusable component for balance card and transcation table
2. create a reuasable component for input
> feat(open-spark): created reusable component

- apps/lend-ease/components/header/constants/index.ts
- apps/lend-ease/pages/index.tsx
1. fixed manage loan cataloug button background color
2. fixed loan tenure amount on home page
3. fixed header on selected category
> fix(lend-ease): fix cosmetic issue

- apps/open-spark-solaris/components/header/constants/index.ts
- apps/open-spark-solaris/pages/orderHistory.tsx
- apps/open-spark-solaris/pages/profile.tsx
- apps/open-spark/pages/orderHistory.tsx
1. added edit icon on profile page
2. remove customer id from profile
3. added dynamic item length on order history and service page
> fix(open-spark): fixed win-room bugs

- apps/open-spark/components/modal/OpenWalletBottomModal.tsx
- apps/open-spark/pages/product.tsx
- apps/retail/pages/orderHistory.tsx
- packages/becknified-components/src/components/product-price/product-price.tsx
1. added select quantity text in product page
2. change order history api url for latest order should be on top
3. change product-price decimal logic
4. added validation on otp verification
> fix(open-spark): ec bug fixes

- apps/lend-ease/components/signIn/SignIn.tsx
- apps/lend-ease/pages/index.tsx
- apps/lend-ease/services/UserService.ts
- apps/lend-ease/utilities/form-utils.ts
- apps/open-spark-solaris/components/signIn/SignIn.tsx
- apps/open-spark-solaris/locales/en.ts
- apps/open-spark-solaris/pages/OTPVerification.tsx
- apps/open-spark-solaris/services/UserService.ts
- apps/open-spark-solaris/store/auth-slice.ts
- apps/open-spark-solaris/utilities/form-utils.ts
- apps/open-spark/components/signIn/SignIn.tsx
- apps/open-spark/locales/en.ts
- apps/open-spark/pages/OTPVerification.tsx
- apps/open-spark/services/UserService.ts
- apps/open-spark/store/auth-slice.ts
- apps/open-spark/utilities/form-utils.ts
- packages/common/lib/types/auth.ts
1. added mobile otp screen for open spark app
2. added mobile otp screen for open solaris app
3. added mobile otp screen for lend ease app
4. added dynamic image from user store for lend ease app
> feat(open-spark): added mobile otp screen

- apps/lend-ease/services/UserService.ts
- apps/open-spark-solaris/pages/index.tsx
- apps/open-spark-solaris/services/UserService.ts
- apps/open-spark/pages/index.tsx
- apps/open-spark/services/UserService.ts
- apps/unified-wallet/pages/physicalAssets.tsx
1. replace login url for all 3 apps
2. spark and solaris app should be connected after link
3. on physical assets show toast message if file is greater than 1 mb
> fix(open-spark): fixed winroom bugs

- apps/open-spark-peer2peer/components/dateRangePicker/SelectDate.tsx
- apps/open-spark-peer2peer/components/energyPurchaseForm/index.tsx
- apps/open-spark-peer2peer/pages/OTPVerification.tsx
- apps/open-spark-peer2peer/pages/index.tsx
- packages/common/src/components/BottomModal/BottomModalScan.tsx
1. otp screen should not allow invalid character
2. added symbol in alert pop up modal
3. added cusror pointer in date range selector
4. remove paranthesis from dashboard card
> fix(open-spark-p2p): fixed issue 3480,3483,3491,3495,3496

- apps/open-spark-peer2peer/components/energyPurchaseForm/index.tsx
- apps/open-spark-peer2peer/components/tab/tab.tsx
- apps/open-spark-peer2peer/pages/index.tsx
- apps/open-spark-peer2peer/pages/myPreference.tsx
- apps/open-spark-peer2peer/store/user-slice.ts
- apps/retail/pages/cart.tsx
1. preffrences should be visible on trade details page if selected
2. data should be persiste while changing screen on buying and selling prefference
3. user should redirect to home page with selected tab
4. solved css issue on cart page for retail app
> fix(open-spark-p2p): fixes ec issue for open spark p2p app

- apps/open-spark-peer2peer/pages/index.tsx
> fix(open-spark-p2p): market showing as closed for 3-5 seconds on login or home page return

- apps/dsnp-v2/pages/orderDetails.tsx
- apps/industry_4.0/components/assemblyDetails/index.tsx
- apps/industry_4.0/pages/orderDetails.tsx
- apps/open-spark-peer2peer/components/currentTrade/EmptyCurrentTrade.tsx
- apps/open-spark-peer2peer/pages/index.tsx
1. empty page added for sell in open spark p2p app
2. remove order details last line if order is completed in industry4.0 app
3. added validation on assembly details page for inustry4.0 app
4. added cursor pointer on rate us text for dsnp app
> fix(EC): fixed experience center bugs

- apps/deg-rental/components/orderOverview/OrderOverview.tsx
- apps/deg-wallet/pages/index.tsx
- apps/retail/pages/orderDetails.tsx
- packages/becknified-components/src/pages/auth/auth.tsx
1. fixed signup ui issue
2. fixed order details ui issue for old retail app
3. fiex order history ui for deg rental app
4. fixed wallet topsheet ui
> fix(deg-retail): fixes deg bug

- apps/OSC/components/geoLocationInput/GeoLocationInputList.tsx
- apps/industry_4.0/components/geoLocationInput/GeoLocationInputList.tsx
- apps/open-spark/components/signUp/signUp.tsx
- apps/retail/components/geoLocationInput/GeoLocationInputList.tsx
- packages/molecules/src/components/input/input.types.ts
> fix(ec): buils issue for retail app and validation fixes for open spark app

- apps/deg-rental/pages/index.tsx
- apps/deg-rental/pages/profile.tsx
- apps/deg-retail/pages/myStore.tsx
- apps/deg-retail/pages/profile.tsx
> fix(deg-retail): fixed cache issue while logout and when user comes to home page

- apps/retail/components/selectDeliveryModal/SelectDeliveryModal.tsx
- apps/retail/pages/search.tsx
> fix(retail): fixed search api should take multiple search keyword using promise.all

- apps/retail/components/selectDeliveryModal/SelectDeliveryModal.tsx
- apps/retail/pages/index.tsx
- apps/retail/pages/search.tsx
- apps/retail/store/index.ts
- packages/common/src/components/searchAndDiscover/searchAndDiscover.tsx
- packages/common/src/store/index.ts
- packages/common/src/store/search-slice.ts
1. added redux search-slice for storing state value
2. changed all state value and use redux store
> fix(retail): fixed search navigation issue

- apps/beckn-registry/pages/index.tsx
- apps/beckn-registry/pages/manageNetworkDomain.tsx
- apps/beckn-registry/pages/manageNetworkParticipants.tsx
- apps/beckn-registry/pages/manageUser/me.tsx
- apps/beckn-registry/pages/manageUser/user.tsx
- apps/beckn-registry/pages/networkDomains.tsx
- apps/beckn-registry/pages/networkParticipants.tsx
- apps/beckn-registry/pages/users.tsx
- apps/beckn-registry/services/networkDomainServices.ts
- apps/beckn-registry/styles/ManageUser.module.css
- apps/beckn-registry/styles/Users.module.css
- Update network domain management functionality
- Improve user management interface and operations
- Refactor network participants management
- Update styling for better user experience
- Optimize service layer for network domain operations
> feat(registry): enhance network domain and user management pages
